"use client";
import { useState, type FormEvent } from "react";
import { useRouter } from "next/navigation";
import { explainError, identity, write } from "@/lib/genlayer";
import { useWallet } from "@/lib/wallet";
export default function NewCheck() {
  const wallet = useWallet(); const router = useRouter(); const [error, setError] = useState(""); const [busy, setBusy] = useState(false);
  async function submit(event: FormEvent<HTMLFormElement>) { event.preventDefault(); setError(""); try { setBusy(true); const form = new FormData(event.currentTarget); await write(identity(wallet.mode, wallet.address, wallet.privateKey), "create_check", [String(form.get("quote")), String(form.get("url")), String(form.get("sourceHash")), String(form.get("meaning")), String(form.get("title"))], BigInt(String(form.get("bond"))) * 10n ** 18n); router.push("/checks"); } catch (caught) { setError(explainError(caught)); } finally { setBusy(false); } }
  return <div className="mx-auto max-w-3xl"><p className="text-xs uppercase tracking-[.25em] text-court-400">New record</p><h1 className="mt-2 font-display text-5xl text-court-100">Check a public quote</h1><p className="mt-3 text-court-200">Commit the exact SHA-256 of the public source: GenLayer will fetch it and refuse to decide if it changes. The bond is released to the quote submitter unless counter-context proves it misleading.</p><form onSubmit={submit} className="mt-8 grid gap-5 border border-court-400/30 bg-court-950/45 p-6"><label>Record title<input name="title" required maxLength={180} placeholder="Minister interview on housing policy" /></label><label>Exact quote<textarea name="quote" required maxLength={1200} placeholder="Paste the words exactly as published." /></label><label>Primary source URL<input name="url" type="url" required placeholder="https://…" /></label><label>Primary source SHA-256<input name="sourceHash" required pattern="0x[0-9a-fA-F]{64}" placeholder="0x…" /></label><label>Claimed meaning<textarea name="meaning" required maxLength={1400} placeholder="Explain how this quote is being represented in the story or newsletter." /></label><label>Bond in GEN<input name="bond" type="number" min="0.001" step="0.001" defaultValue="0.01" required /></label>{!wallet.address ? <p className="text-sm text-court-400">Connect a wallet before creating a record.</p> : null}{error ? <p className="border border-red-400/50 p-3 text-sm text-red-200">{error}</p> : null}<button disabled={!wallet.address || busy} className="rounded-md bg-court-400 px-5 py-3 font-bold text-court-950 disabled:opacity-50">{busy ? "Waiting for finalization…" : "Create quote check"}</button></form></div>;
}
